version: '3.9'
networks:
  comics_shop_network:
    external: true
services:
  comics_shop_rpc:
    container_name: comics_shop_rpc
    image: mcr.microsoft.com/dotnet/sdk:6.0-focal
    command: "dotnet watch run --urls=http://+:8092"
    working_dir: /app
    networks:
      - comics_shop_network
    ports:
      - 8092:8092
    volumes:
      - './:/app'
    environment:
      - ASPNETCORE_URLS=http://+:8092
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=server=database_comics_shop;port=3306;database=comics_shop;user=comics_shop;password=password